swagger: "2.0"
info:
    title: Bank Argent API documentation - Transactions
    description: Contains all API endpoints for user's transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
    /user/transactions:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transactions Current Month API
            description: Showing current month transactions
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: User transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/TransactionsResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
    /user/transaction/{idTransaction}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Show API
            description: Showing one transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/TransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Transaction Edit API
            description: Updating a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: idTransaction
                  description: Id of the transaction that needs to be edited
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Edit transaction
                  required: true
                  schema:
                      $ref: "#/definitions/editTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/TransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    TransactionsResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    account_type_1: 
                        type: object
                        properties:
                            id:
                                type: string
                                description: Id of Current account
                            name:
                                type: string
                                description: Current account
                    account_type_2: 
                        type: object
                        properties:
                            id:
                                type: string
                                description: Id of Saving account
                            name:
                                type: string
                                description: Saving account
                    account_type_3: 
                        type: object
                        properties:
                            id:
                                type: string
                                description: Id of Credit account
                            name:
                                type: string
                                description: Credit account
                    transaction_1:
                        type: object
                        description: First transaction
                        properties:
                            id:
                                type: string
                                description: Id of the first transaction
                            account:
                                type: string
                                description: Account type of the first transaction
                            date:
                                type: string
                                description: Date of the first transaction
                            amount:
                                type: number
                                description: Amount of the first transaction
                            description:
                                type: string
                                description: Description of the first transaction
                            category:
                                type: string
                                description: Category of the first transaction
                    transaction_2:
                        type: object
                        description: Second transaction
                        properties:
                            id:
                                type: string
                                description: Id of the second transaction
                            account:
                                type: string
                                description: Account type of the second transaction
                            date:
                                type: string
                                description: Date of the second transaction
                            amount:
                                type: number
                                description: Amount of the second transaction
                            description:
                                type: string
                                description: Description of the second transaction
                            category:
                                type: string
                                description: Category of the second transaction
                    transaction_3:
                        type: object
                        description: Third transaction
                        properties:
                            id:
                                type: string
                                description: Id of the third transaction
                            account:
                                type: string
                                description: Account type of the third transaction
                            date:
                                type: string
                                description: Date of the third transaction
                            amount:
                                type: number
                                description: Amount of the third transaction
                            description:
                                type: string
                                description: Description of the third transaction
                            category:
                                type: string
                                description: Category of the third transaction
    FilteredTransactionsResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    transaction_1:
                        type: object
                        description: First transaction
                        properties:
                            id:
                                type: string
                                description: Id of the first transaction
                            account:
                                type: string
                                description: Account type of the first transaction
                            date:
                                type: string
                                description: Date of the first transaction
                            amount:
                                type: number
                                description: Amount of the first transaction
                            description:
                                type: string
                                description: Description of the first transaction
                            category:
                                type: string
                                description: Category of the first transaction
                    transaction_2:
                        type: object
                        description: Second transaction
                        properties:
                            id:
                                type: string
                                description: Id of the second transaction
                            account:
                                type: string
                                description: Account type of the second transaction
                            date:
                                type: string
                                description: Date of the second transaction
                            amount:
                                type: number
                                description: Amount of the second transaction
                            description:
                                type: string
                                description: Description of the second transaction
                            category:
                                type: string
                                description: Category of the second transaction
                    transaction_3:
                        type: object
                        description: Third transaction
                        properties:
                            id:
                                type: string
                                description: Id of the third transaction
                            account:
                                type: string
                                description: Account type of the third transaction
                            date:
                                type: string
                                description: Date of the third transaction
                            amount:
                                type: number
                                description: Amount of the third transaction
                            description:
                                type: string
                                description: Description of the third transaction
                            category:
                                type: string
                                description: Category of the third transaction
    TransactionResponse:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    account:
                        type: string
                        description: Account type of the transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
    addInformation:
        properties:
            category:
                type: string
                description: Add a category to this transaction
            description:
                type: string
                description: Add a description to this transaction
            account:
                type: string
                description: Add the account's type of this transaction
    editTransaction:
        properties:
            category:
                type: string
                description: Edit category of this transaction
            description:
                type: string
                description: Edit description of this transaction
            account:
                type: string
                description: Edit the account's type of this transaction
    deleteInformation:
        properties:
            category:
                type: string
                description: Delete a category to this transaction
            description:
                type: string
                description: Delete a description to this transaction
            account:
                type: string
                description: Delete the account's type of this transaction
